@startwbs UC013
* 0. Undo/Redo operations
** 1. Open in editor
*** 1.1 Locate photo(s)
*** 1.2 Click thumbnail(s)
** 2. Undo
*** 2.1 Click "Undo"
** 3. Redo (opt.)
*** 3.1 Click "Redo"
** 4. Review changes
@endwbs
