@startwbs UC003
* 0. Assign photo to collection
** 1. Locate photo
*** 1.1 In gallery: scroll
*** 1.2 In collection:\nclick "See Collection"\nthen scroll
** 2. Start assignment
*** 2.1 Click checkbox
*** 2.2 Collection Selector opens
** 3. Choose collection
*** 3.1 Click collection
*** 3.2 Or click "Create New"
** 4. Confirm assignment
*** 4.1 View confirmation
@endwbs
